import { cn } from "@/lib/utils/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Teko } from "next/font/google";

const teko = Teko({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Startup Nation",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-black h-full", teko.className)}>{children}</body> 
    </html>
  );
}
