import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Filter from "./cat-filter";
import { readItems, rest, createDirectus } from "@directus/sdk";
import Container from "@/components/container";
import Header from "@/components/home/header/Header";
import Hero from "@/components/directory/hero";
import ShowPath from "@/components/directory/showPath";
import Footer from "@/components/footer/footer";
import { ChevronLeft, ChevronRight } from "lucide-react";
import Search from "./searchBar";
import { Teko } from "next/font/google";

const teko = Teko({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const directusClient = createDirectus(
    "https://startupnation.panel.dreamslab.dev/"
  ).with(rest());
  const cat = await directusClient.request(readItems("Category", {}));
  return (
    <html lang="en">
      <body className={teko.className}>
        <Container>
          <Header />
          <Hero
            cover="/image/la.gif"
            title="Startup Directory"
            subtitle="Lorem ipsum dolor sit amet consectetur. Venenatis nec sodales
              semper nec rhoncus leo arcu ultricies tincidunt."
          />
          <div className="bg-black text-white py-5 font-body">
            <ShowPath className="mb-5" />
            <div className="md:flex justify-between gap-8 w-[100%] md:h-16 h-[100px]">
              <Filter category={cat} />
              <Search />
            </div>
          </div>
          <div>{children}</div>
          {/* pagination bar */}
          <div className="flex justify-between items-center mt-10 py-5 w-full border-t-2 border-gray-400">
            <div>1 -6 from 100</div>
            <div className="flex justify-between gap-10">
              <ChevronLeft className="w-6 h-6" />
              {/* <div className="flex">
                    {numPage.map((num) => (
                      <p
                        key={num}
                        className={`border-2 px-5 ml-2 hover:bg-gray-600 cursor-pointer`}
                      >
                        {num}
                      </p>
                    ))}
                  </div> */}
              <ChevronRight className="w-6 h-6" />
            </div>
            <div>Show rows </div>
          </div>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
